# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/Documents/pmsweng/SpicyPP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/Documents/pmsweng/SpicyPP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Documents/pmsweng/SpicyPP/CMakeFiles /home/user/Documents/pmsweng/SpicyPP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Documents/pmsweng/SpicyPP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named matrix

# Build rule for target.
matrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix
.PHONY : matrix

# fast build rule for target.
matrix/fast:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/build
.PHONY : matrix/fast

#=============================================================================
# Target rules for targets named spicy

# Build rule for target.
spicy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spicy
.PHONY : spicy

# fast build rule for target.
spicy/fast:
	$(MAKE) -f CMakeFiles/spicy.dir/build.make CMakeFiles/spicy.dir/build
.PHONY : spicy/fast

#=============================================================================
# Target rules for targets named tests_autogen

# Build rule for target.
tests_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests_autogen
.PHONY : tests_autogen

# fast build rule for target.
tests_autogen/fast:
	$(MAKE) -f CMakeFiles/tests_autogen.dir/build.make CMakeFiles/tests_autogen.dir/build
.PHONY : tests_autogen/fast

#=============================================================================
# Target rules for targets named matrix_autogen

# Build rule for target.
matrix_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_autogen
.PHONY : matrix_autogen

# fast build rule for target.
matrix_autogen/fast:
	$(MAKE) -f CMakeFiles/matrix_autogen.dir/build.make CMakeFiles/matrix_autogen.dir/build
.PHONY : matrix_autogen/fast

#=============================================================================
# Target rules for targets named spicy_autogen

# Build rule for target.
spicy_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spicy_autogen
.PHONY : spicy_autogen

# fast build rule for target.
spicy_autogen/fast:
	$(MAKE) -f CMakeFiles/spicy_autogen.dir/build.make CMakeFiles/spicy_autogen.dir/build
.PHONY : spicy_autogen/fast

matrix_autogen/mocs_compilation.o: matrix_autogen/mocs_compilation.cpp.o

.PHONY : matrix_autogen/mocs_compilation.o

# target to build an object file
matrix_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/matrix_autogen/mocs_compilation.cpp.o
.PHONY : matrix_autogen/mocs_compilation.cpp.o

matrix_autogen/mocs_compilation.i: matrix_autogen/mocs_compilation.cpp.i

.PHONY : matrix_autogen/mocs_compilation.i

# target to preprocess a source file
matrix_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/matrix_autogen/mocs_compilation.cpp.i
.PHONY : matrix_autogen/mocs_compilation.cpp.i

matrix_autogen/mocs_compilation.s: matrix_autogen/mocs_compilation.cpp.s

.PHONY : matrix_autogen/mocs_compilation.s

# target to generate assembly for a file
matrix_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/matrix_autogen/mocs_compilation.cpp.s
.PHONY : matrix_autogen/mocs_compilation.cpp.s

spicy_autogen/mocs_compilation.o: spicy_autogen/mocs_compilation.cpp.o

.PHONY : spicy_autogen/mocs_compilation.o

# target to build an object file
spicy_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/spicy.dir/build.make CMakeFiles/spicy.dir/spicy_autogen/mocs_compilation.cpp.o
.PHONY : spicy_autogen/mocs_compilation.cpp.o

spicy_autogen/mocs_compilation.i: spicy_autogen/mocs_compilation.cpp.i

.PHONY : spicy_autogen/mocs_compilation.i

# target to preprocess a source file
spicy_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/spicy.dir/build.make CMakeFiles/spicy.dir/spicy_autogen/mocs_compilation.cpp.i
.PHONY : spicy_autogen/mocs_compilation.cpp.i

spicy_autogen/mocs_compilation.s: spicy_autogen/mocs_compilation.cpp.s

.PHONY : spicy_autogen/mocs_compilation.s

# target to generate assembly for a file
spicy_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/spicy.dir/build.make CMakeFiles/spicy.dir/spicy_autogen/mocs_compilation.cpp.s
.PHONY : spicy_autogen/mocs_compilation.cpp.s

src/Backend/Matrix.o: src/Backend/Matrix.cpp.o

.PHONY : src/Backend/Matrix.o

# target to build an object file
src/Backend/Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/src/Backend/Matrix.cpp.o
.PHONY : src/Backend/Matrix.cpp.o

src/Backend/Matrix.i: src/Backend/Matrix.cpp.i

.PHONY : src/Backend/Matrix.i

# target to preprocess a source file
src/Backend/Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/src/Backend/Matrix.cpp.i
.PHONY : src/Backend/Matrix.cpp.i

src/Backend/Matrix.s: src/Backend/Matrix.cpp.s

.PHONY : src/Backend/Matrix.s

# target to generate assembly for a file
src/Backend/Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/src/Backend/Matrix.cpp.s
.PHONY : src/Backend/Matrix.cpp.s

src/Backend/Matrix_test.o: src/Backend/Matrix_test.cpp.o

.PHONY : src/Backend/Matrix_test.o

# target to build an object file
src/Backend/Matrix_test.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Backend/Matrix_test.cpp.o
.PHONY : src/Backend/Matrix_test.cpp.o

src/Backend/Matrix_test.i: src/Backend/Matrix_test.cpp.i

.PHONY : src/Backend/Matrix_test.i

# target to preprocess a source file
src/Backend/Matrix_test.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Backend/Matrix_test.cpp.i
.PHONY : src/Backend/Matrix_test.cpp.i

src/Backend/Matrix_test.s: src/Backend/Matrix_test.cpp.s

.PHONY : src/Backend/Matrix_test.s

# target to generate assembly for a file
src/Backend/Matrix_test.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Backend/Matrix_test.cpp.s
.PHONY : src/Backend/Matrix_test.cpp.s

src/Backend/Network.o: src/Backend/Network.cpp.o

.PHONY : src/Backend/Network.o

# target to build an object file
src/Backend/Network.cpp.o:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/src/Backend/Network.cpp.o
.PHONY : src/Backend/Network.cpp.o

src/Backend/Network.i: src/Backend/Network.cpp.i

.PHONY : src/Backend/Network.i

# target to preprocess a source file
src/Backend/Network.cpp.i:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/src/Backend/Network.cpp.i
.PHONY : src/Backend/Network.cpp.i

src/Backend/Network.s: src/Backend/Network.cpp.s

.PHONY : src/Backend/Network.s

# target to generate assembly for a file
src/Backend/Network.cpp.s:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/src/Backend/Network.cpp.s
.PHONY : src/Backend/Network.cpp.s

src/Backend/Resistor.o: src/Backend/Resistor.cpp.o

.PHONY : src/Backend/Resistor.o

# target to build an object file
src/Backend/Resistor.cpp.o:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/src/Backend/Resistor.cpp.o
.PHONY : src/Backend/Resistor.cpp.o

src/Backend/Resistor.i: src/Backend/Resistor.cpp.i

.PHONY : src/Backend/Resistor.i

# target to preprocess a source file
src/Backend/Resistor.cpp.i:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/src/Backend/Resistor.cpp.i
.PHONY : src/Backend/Resistor.cpp.i

src/Backend/Resistor.s: src/Backend/Resistor.cpp.s

.PHONY : src/Backend/Resistor.s

# target to generate assembly for a file
src/Backend/Resistor.cpp.s:
	$(MAKE) -f CMakeFiles/matrix.dir/build.make CMakeFiles/matrix.dir/src/Backend/Resistor.cpp.s
.PHONY : src/Backend/Resistor.cpp.s

src/Frontend/MainWindow.o: src/Frontend/MainWindow.cpp.o

.PHONY : src/Frontend/MainWindow.o

# target to build an object file
src/Frontend/MainWindow.cpp.o:
	$(MAKE) -f CMakeFiles/spicy.dir/build.make CMakeFiles/spicy.dir/src/Frontend/MainWindow.cpp.o
.PHONY : src/Frontend/MainWindow.cpp.o

src/Frontend/MainWindow.i: src/Frontend/MainWindow.cpp.i

.PHONY : src/Frontend/MainWindow.i

# target to preprocess a source file
src/Frontend/MainWindow.cpp.i:
	$(MAKE) -f CMakeFiles/spicy.dir/build.make CMakeFiles/spicy.dir/src/Frontend/MainWindow.cpp.i
.PHONY : src/Frontend/MainWindow.cpp.i

src/Frontend/MainWindow.s: src/Frontend/MainWindow.cpp.s

.PHONY : src/Frontend/MainWindow.s

# target to generate assembly for a file
src/Frontend/MainWindow.cpp.s:
	$(MAKE) -f CMakeFiles/spicy.dir/build.make CMakeFiles/spicy.dir/src/Frontend/MainWindow.cpp.s
.PHONY : src/Frontend/MainWindow.cpp.s

src/Frontend/SpicyPP.o: src/Frontend/SpicyPP.cpp.o

.PHONY : src/Frontend/SpicyPP.o

# target to build an object file
src/Frontend/SpicyPP.cpp.o:
	$(MAKE) -f CMakeFiles/spicy.dir/build.make CMakeFiles/spicy.dir/src/Frontend/SpicyPP.cpp.o
.PHONY : src/Frontend/SpicyPP.cpp.o

src/Frontend/SpicyPP.i: src/Frontend/SpicyPP.cpp.i

.PHONY : src/Frontend/SpicyPP.i

# target to preprocess a source file
src/Frontend/SpicyPP.cpp.i:
	$(MAKE) -f CMakeFiles/spicy.dir/build.make CMakeFiles/spicy.dir/src/Frontend/SpicyPP.cpp.i
.PHONY : src/Frontend/SpicyPP.cpp.i

src/Frontend/SpicyPP.s: src/Frontend/SpicyPP.cpp.s

.PHONY : src/Frontend/SpicyPP.s

# target to generate assembly for a file
src/Frontend/SpicyPP.cpp.s:
	$(MAKE) -f CMakeFiles/spicy.dir/build.make CMakeFiles/spicy.dir/src/Frontend/SpicyPP.cpp.s
.PHONY : src/Frontend/SpicyPP.cpp.s

tests_autogen/mocs_compilation.o: tests_autogen/mocs_compilation.cpp.o

.PHONY : tests_autogen/mocs_compilation.o

# target to build an object file
tests_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_autogen/mocs_compilation.cpp.o
.PHONY : tests_autogen/mocs_compilation.cpp.o

tests_autogen/mocs_compilation.i: tests_autogen/mocs_compilation.cpp.i

.PHONY : tests_autogen/mocs_compilation.i

# target to preprocess a source file
tests_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_autogen/mocs_compilation.cpp.i
.PHONY : tests_autogen/mocs_compilation.cpp.i

tests_autogen/mocs_compilation.s: tests_autogen/mocs_compilation.cpp.s

.PHONY : tests_autogen/mocs_compilation.s

# target to generate assembly for a file
tests_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests_autogen/mocs_compilation.cpp.s
.PHONY : tests_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... tests"
	@echo "... edit_cache"
	@echo "... matrix"
	@echo "... test"
	@echo "... spicy"
	@echo "... tests_autogen"
	@echo "... matrix_autogen"
	@echo "... spicy_autogen"
	@echo "... matrix_autogen/mocs_compilation.o"
	@echo "... matrix_autogen/mocs_compilation.i"
	@echo "... matrix_autogen/mocs_compilation.s"
	@echo "... spicy_autogen/mocs_compilation.o"
	@echo "... spicy_autogen/mocs_compilation.i"
	@echo "... spicy_autogen/mocs_compilation.s"
	@echo "... src/Backend/Matrix.o"
	@echo "... src/Backend/Matrix.i"
	@echo "... src/Backend/Matrix.s"
	@echo "... src/Backend/Matrix_test.o"
	@echo "... src/Backend/Matrix_test.i"
	@echo "... src/Backend/Matrix_test.s"
	@echo "... src/Backend/Network.o"
	@echo "... src/Backend/Network.i"
	@echo "... src/Backend/Network.s"
	@echo "... src/Backend/Resistor.o"
	@echo "... src/Backend/Resistor.i"
	@echo "... src/Backend/Resistor.s"
	@echo "... src/Frontend/MainWindow.o"
	@echo "... src/Frontend/MainWindow.i"
	@echo "... src/Frontend/MainWindow.s"
	@echo "... src/Frontend/SpicyPP.o"
	@echo "... src/Frontend/SpicyPP.i"
	@echo "... src/Frontend/SpicyPP.s"
	@echo "... tests_autogen/mocs_compilation.o"
	@echo "... tests_autogen/mocs_compilation.i"
	@echo "... tests_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

