add_test( MatrixTest.InverseTest /home/user/Documents/SpicyPP/tests [==[--gtest_filter=MatrixTest.InverseTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( MatrixTest.InverseTest PROPERTIES WORKING_DIRECTORY /home/user/Documents/SpicyPP)
add_test( MatrixTest.InverseSingularFailTest /home/user/Documents/SpicyPP/tests [==[--gtest_filter=MatrixTest.InverseSingularFailTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( MatrixTest.InverseSingularFailTest PROPERTIES WORKING_DIRECTORY /home/user/Documents/SpicyPP)
add_test( MatrixTest.InverseMatrixBeginningWithZero /home/user/Documents/SpicyPP/tests [==[--gtest_filter=MatrixTest.InverseMatrixBeginningWithZero]==] --gtest_also_run_disabled_tests)
set_tests_properties( MatrixTest.InverseMatrixBeginningWithZero PROPERTIES WORKING_DIRECTORY /home/user/Documents/SpicyPP)
add_test( MatrixTest.InverseNonNxNMatrix /home/user/Documents/SpicyPP/tests [==[--gtest_filter=MatrixTest.InverseNonNxNMatrix]==] --gtest_also_run_disabled_tests)
set_tests_properties( MatrixTest.InverseNonNxNMatrix PROPERTIES WORKING_DIRECTORY /home/user/Documents/SpicyPP)
set( tests_TESTS MatrixTest.InverseTest MatrixTest.InverseSingularFailTest MatrixTest.InverseMatrixBeginningWithZero MatrixTest.InverseNonNxNMatrix)
